[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
srun: error: gpu15: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
Traceback (most recent call last):
  File "cifar10_deepspeed.py", line 245, in <module>
    model_engine, optimizer, trainloader, __ = deepspeed.initialize(
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 261, in __init__
    self._do_args_sanity_check(args)
  File "/home01/hpc72a03/.conda/envs/lightning/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 897, in _do_args_sanity_check
    assert "LOCAL_RANK" in os.environ or "OMPI_COMM_WORLD_LOCAL_RANK" in os.environ, "DeepSpeed requires the LOCAL_RANK environment " \
AssertionError: DeepSpeed requires the LOCAL_RANK environment variable, it is set by the deepspeed launcher, deepspeed.init_distributed, or the torch's launcher. If using a different launcher please ensure LOCAL_RANK is set prior to initializing deepspeed.
srun: error: gpu15: tasks 1,3: Exited with exit code 1
srun: error: gpu16: tasks 4-6: Exited with exit code 1
srun: error: gpu15: task 2: Exited with exit code 1
srun: error: gpu16: task 7: Exited with exit code 1
